# Meta Data for SEO

## Homepage
title = "fnrun"
titleSeparator = "-"
titleAddition = "Build and run business functions with ease"
description = "fnrun is a project that helps you build and execute business function runners"

## Open Graph + Twitter Cards
images = ["fnrun.png"]
twitterSite = "fnrundev"
twitterCreator = "fnrundev"
# facebookAuthor = "verlinde.henk"
# facebookPublisher = "verlinde.henk"
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "fnrun.png"
schemaTwitter = "https://twitter.com/fnrundev"
# schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/fnrun"
# schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like fnrun? <a class=\"alert-link\" href=\"https://github.com/fnrun/fnrun/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/fnrun/website"
editPage = true
